name: Assign auto

on:
  pull_request:
    types: reopened

jobs:
  assign:
    name: Set assignees and reviewers
    runs-on: ubuntu-latest
    steps:
      - name: Set assignees
        env:
          # プルリクエストを開いたユーザーのGitHubのユーザー名
          ASSIGNEES: "${{ github.actor }}"
        run: |
          assignee_count=$(cat ${{ github.event_path }} | jq '.pull_request.assignees | length')
          if [[ 0 == $assignee_count ]]; then
            curl -X POST \
              -H "Content-Type: application/json" \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -d "{ \"assignees\": \"${{ github.actor }}\" }" \
              https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/assignees
          fi
      