name: Automatically labeling pull request.

on:
  pull_request:
    types: [opened]

jobs:
  auto-labeling-pr:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      # ラベル名を取得する
      # github.head_ref はブランチ名を取得する
      # cut -d "/" -f1 で "/" で区切った最初の要素を取得する
      # echo "label_name=$label_name" >> $GITHUB_env で label_name という名前を環境変数に出力する
      - name: Get label name
        id: label_name
        run: |
          branch_type=$(echo ${{github.head_ref}} | cut -d "/" -f1)
          if [ $branch_type == 'feature' ]; then
            label_name=$(echo "enhancement")
          elif [ $branch_type == 'fix' ] || [ $branch_type == 'hotfix' ]; then
            label_name=$(echo "bug")
          elif [ $branch_type == 'release' ]; then
            label_name=$(echo "release")
          elif [ $branch_type == 'improvement' ]; then
            label_name=$(echo "improvement")
          elif [ $branch_type == 'chore' ]; then
            label_name=$(echo "chore")
          else
            label_name=""
          fi
          echo "label_name=$label_name" >> $GITHUB_ENV

      # PRにラベルを付与する
      - name: Auto labeling
        if: ${{ env.label_name }}
        run: |
          number=$(echo $GITHUB_REF | sed -e 's/[^0-9]//g')
          gh pr edit $number --add-label ${{ env.label_name }}
